modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="moremobvariants"
    version="1.21.11-1.0.0"
    displayName="Enhanced Mob Variants"
    authors="Astryxion"
    description="Adds unique visual variants to vanilla mobs to improve world diversity."

[[dependencies.moremobvariants]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moremobvariants]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"