org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

minecraft_version=1.7.10
forge_version=10.13.4.1614

## Mod Properties

mod_id=emv
mod_name=Enhanced Mob Variants
mod_license=GPL-3.0
mod_version=1.7.10-1.3.0
mod_group_id=com.astryxion.emv
mod_authors=Astryxion
mod_description=Adds unique visual variants to vanilla mobs to improve world diversity.
archives_base_name=emvforge
